/* File automatically generated by fixincludes.gcc
   on: Sun Dec 21 18:13:14 PST 2003
   at: Linux linux 2.4.19-4GB #1 Fri Sep 13 13:14:56 UTC 2002 i586 unknown
*/
static const char * const search_dirs [] = {
	"/usr/local/include",
	"/usr/lib/gcc-lib/i486-suse-linux/3.2/include",
	"/usr/i486-suse-linux/include",
	"/usr/include",
	0
};

/* Host compiler defines */
static const char sys_defs [] = 
"#define __HAVE_BUILTIN_SETJMP__ 1\n"
"#define __unix__ 1\n"
"#define unix 1\n"
"#define __i386__ 1\n"
"#define __SIZE_TYPE__ unsigned int\n"
"#define __ELF__ 1\n"
"#define __GNUC_PATCHLEVEL__ 0\n"
"#define __linux 1\n"
"#define __OPTIMIZE__ 1\n"
"#define __unix 1\n"
"#define __linux__ 1\n"
"#define __USER_LABEL_PREFIX__ \n"
"#define linux 1\n"
"#define __STDC_HOSTED__ 1\n"
"#define __WCHAR_TYPE__ long int\n"
"#define __gnu_linux__ 1\n"
"#define __WINT_TYPE__ unsigned int\n"
"#define __GNUC__ 3\n"
"#define __tune_i486__ 1\n"
"#define __GXX_ABI_VERSION 102\n"
"#define i386 1\n"
"#define __GNUC_MINOR__ 2\n"
"#define __STDC__ 1\n"
"#define __PTRDIFF_TYPE__ int\n"
"#define __REGISTER_PREFIX__ \n"
"#define __i386 1\n"
"#define __VERSION__ \"3.2\"\n"
"";

//#define DO_CPP
